parameters:
#    ordenamiento.example.class: Test\ClickBus\OrdenamientoBundle\Example

services:
#    ordenamiento.example:
#        class: %ordenamiento.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
