parameters:
#    cajero.example.class: Test\ClickBus\CajeroBundle\Example

services:
#    cajero.example:
#        class: %cajero.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
